---
title: "Impala.AJE"
author: "Matt Wuensch"
date: "11/20/2024"
output: html_document
editor_options: 
  chunk_output_type: console
---
# Chunk 1: 2017 analyses
```{r}
# 2017 data summary and analysis
library(dplyr)

# Bring in datatframe
imp.dat.17 <- read.csv("C:/Users/mwuen/Documents/R/Misc/Impala/impala.data.17.csv")
imp.dat.17 <-  read.csv("~/Desktop/KSU_Research/South Africa/Impala/impala.data.17.csv")


# Convert to factor
imp.dat.17$location <- as.factor(imp.dat.17$location)
imp.dat.17$impala.type <- as.factor(imp.dat.17$impala.type)
imp.dat.17$herd.type <- as.factor(imp.dat.17$herd.type)
str(imp.dat.17)

# Get summary of each behavior type for each location, herd type, and impala type for each behavior
imp.dat.17.sum <- imp.dat.17 %>%
  group_by(location,herd.type,impala.type) %>%
  summarise_if(is.integer, sum) %>%
  ungroup()


# 2017 Chisq
chisq.test(imp.dat.17.sum[,c(4:6)], correct = FALSE)
  # x2 stat = 41.899, df = 4, p = 1.75e-08

## Pairwise comparisons
### Female - Juvenile
chisq.test(imp.dat.17.sum[c(1,2),c(4:6)], correct = FALSE)
  # x2 stat = 4.5592, df = 2, p = 0.1023

### Female - Male
chisq.test(imp.dat.17.sum[c(1,3),c(4:6)], correct = FALSE)
  # x2 stat = 35.061, df = 2, p = 2.436e-08

### Male - Juvenile
chisq.test(imp.dat.17.sum[c(2,3),c(4:6)], correct = FALSE)
  # x2 stat = 28.855, df = 2, p = 5.424e-07
```
# Chunk 2: 2023 analyses
```{r}
library(dplyr)

# Bring in datatframe
imp.dat.23 <- read.csv("C:/Users/mwuen/Documents/R/Misc/Impala/impala.data.23.csv")
imp.dat.23 <-  read.csv("~/Desktop/KSU_Research/South Africa/Impala/impala.data.23.csv")

# Convert to factor
imp.dat.23$location <- as.factor(imp.dat.23$location)
imp.dat.23$impala.type <- as.factor(imp.dat.23$impala.type)
imp.dat.23$herd.type <- as.factor(imp.dat.23$herd.type)
str(imp.dat.23)

# Get summary of each behavior type for each location, herd type, and impala type for each behavior
imp.dat.23.sum <- imp.dat.23 %>%
  group_by(location,herd.type,impala.type) %>%
  summarise_if(is.integer, sum) %>%
  ungroup()

# remove juveniles in Kruger, students only gathered data from 2 individuals over short timespan. Also remove f/j from bachelor herds
imp.dat.23.sum<- imp.dat.23.sum[-c(1,2,5,7,8),]


# REMINDER: Q1 is how does impala behavior vary within territorial herds
#               1 chisq in each WRF (F-J, F-M, M-J) and KNP (F-M)            
#           Q2 is how does behavior vary among territorial and bachelor males
#               1 chisq in each WRF and KNP (TERR-BACH)  
#           Q3 is how does behavior vary between KNP and WRF
#               2 chisqs in total. 1 for territorial herd, 1 for bach herd. if I don't like this



##### Q1 Impala behavior in territorial herds #####

# Filter for territorial herds
imp.23.ter.sum <- imp.dat.23.sum %>%
  filter(herd.type == "territorial")

# Split into each location
wits.23.ter.dat <- imp.23.ter.sum %>%
  filter(location == "wits.facility")

kru.23.ter.dat <- imp.23.ter.sum %>%
  filter(location == "kruger")



# 2023 Wits code, Q1
chisq.test(wits.23.ter.dat[,c(4:6)], correct = FALSE)
  # x2 stat = 169.47, df = 4, p < 2.2e-16

## Pairwise comparisons
### Female - Juvenile
chisq.test(wits.23.ter.dat[c(1,2),c(4:6)], correct = FALSE)
  # x2 stat = 99.332, df = 2, p < 2.2e-16

### Female - Male
chisq.test(wits.23.ter.dat[c(1,3),c(4:6)], correct = FALSE)
  # x2 stat = 91.427, df = 2, p < 2.2e-16

### Male - Juvenile
chisq.test(wits.23.ter.dat[c(2,3),c(4:6)], correct = FALSE)
  # x2 stat = 20.369, df = 2, p < 2.2e-16


# 2023 kruger code (F-M only), Q1
chisq.test(kru.23.ter.dat[,c(4:6)], correct = FALSE)
  # x2 stat = 14.196, df = 2, p = 0.0008269



##### Q2 Impala behavior between males in bachelor and territorial herds #####

# Filter for males
imp.23.male.sum <- imp.dat.23.sum %>%
  filter(impala.type == "male")


# 2023 Bachelor - territorial code, Q2
chisq.test(imp.23.male.sum[,c(4:6)], correct = FALSE)
# x2 stat = 62.189, df = 6, p = 1.615e-11

## Pairwise comparisons
### WRF bachelor - territorial
chisq.test(imp.23.male.sum[c(3,4),c(4:6)], correct = FALSE)
# x2 stat = 48.499, df = 2, p = 2.941e-11

## KNP bachelor - territorial
chisq.test(imp.23.male.sum[c(1,2),c(4:6)], correct = FALSE)
# x2 stat = 7.8455, df = 2, p = 0.01979



##### Q3 Impala behavior between kruger NP and WRF #####


# Remove juveniles from imp.ter.sum since they're not in kruger
imp.23.ter.sum.2 <- imp.23.ter.sum[-4,]


# 2023 Territorial code, Q3
chisq.test(imp.23.ter.sum.2[,c(4:6)], correct = FALSE)
  # x2 stat = 156.39, df = 6, p < 2.2e-16

## Pairwise comparisons
### KNP female - WRF female
chisq.test(imp.23.ter.sum.2[c(1,3),c(4:6)], correct = FALSE)
  # x2 stat = 103.12, df = 2, p < 2.2e-16

### KNP male - WRF male
chisq.test(imp.23.ter.sum.2[c(2,4),c(4:6)], correct = FALSE)
  # x2 stat = 23.2, df = 2, p = 9.165e-06



# 2023 Bachelor code, Q3
chisq.test(imp.23.male.sum[c(1,3),c(4:6)], correct = FALSE)
  # x2 stat = 8.1226, df = 2, p = 0.01723
```
# Chunk 3: Figures
```{r}
library(ggplot2)
library(tidyr)

# Notes for Taylor: I haven't made a 2017 figure yet (we only have data from WRF in territorial herds there). It'll be easy to adapt the 2023 code. I'm also not remotely married to any of these color palettes so change whatever the hell you want. I also did colors by behavior type, if you think it makes more sense to color impala type, herd type, etc differently, that works too! I also don't think I have the fonts set to print nicely at a given size since I made these REALLY fast for Ellie. Note to self, check orders of x axes.

##### 2017 Figures (Need done following code for 2023) #####
imp.dat.17.sum

## Territorial herds (only have WRF data from this year, all on territorial herds)
# Need to convert everything to long format
imp.ter.17.long <- imp.dat.17.sum %>%
  pivot_longer(
    cols = c("foraging", "vigilant", "all.other"),
    names_to = "Behavior",
    values_to = "Count"
  )

# Need to get total observations for each group to convert counts to proportions
imp.ter.17.long <- imp.ter.17.long %>%
   group_by(location, impala.type) %>%
  mutate(sum = sum(Count))

# Making a proportion column
imp.ter.17.long$prop <- imp.ter.17.long$Count/imp.ter.17.long$sum

#Reorder and rename behavior levels
imp.ter.17.long$Behavior<-factor(imp.ter.17.long$Behavior, levels=c("foraging", "vigilant", "all.other"), labels= c("Foraging", "Vigilance", "Other"))

# Setting theme for plots that I like
theme <- theme_classic()+
  theme(axis.title = element_text(size = 12), text = element_text(size = 10), axis.text=element_text(size=10, color = "black"), legend.title=element_text(size=10), legend.text=element_text(size=10), legend.position="right", axis.title.x = element_blank())



# Making plot for territorial herds
Figure.1 <- ggplot(data = imp.ter.17.long, aes(y = prop, x= interaction(impala.type, location), fill = Behavior)) + 
  geom_bar(position = "dodge", stat = "identity", alpha = .85) + 
  theme +
    scale_fill_manual(values = c("#488650", "#4C0C0B", "#A0A0A0"))+
  ylab("Proportion of time") +
theme(axis.title.x = element_text(size=12))+
xlab("Impala type & location") +
scale_x_discrete(limits= c( "female.wits.facility", "male.wits.facility", "juvenile.wits.facility"), labels=c("Female.WRF", "Male.WRF", "Juvenile.WRF"))
Figure.1





##### 2023 Figures #####

## Territorial herds
# Need to convert everything to long format
imp.23.ter.long <- imp.23.ter.sum %>%
  pivot_longer(
    cols = c("foraging", "vigilant", "all.other"),
    names_to = "Behavior",
    values_to = "Count"
  )

# Need to get total observations for each group to convert counts to proportions
imp.23.ter.long <- imp.23.ter.long %>%
   group_by(location, impala.type) %>%
  mutate(sum = sum(Count))

# Making a proportion column
imp.23.ter.long$prop <- imp.23.ter.long$Count/imp.23.ter.long$sum

#Reorder and rename behavior levels
imp.23.ter.long$Behavior<-factor(imp.23.ter.long$Behavior, levels=c("foraging", "vigilant", "all.other"), labels= c("Foraging", "Vigilance", "Other"))



# Making plot for territorial herds
Figure.2 <- ggplot(data = imp.23.ter.long, aes(y = prop, x= interaction(impala.type, location), fill = Behavior)) + 
  geom_bar(position = "dodge", stat = "identity", alpha = .85) + 
  theme +
    scale_fill_manual(values = c("#488650", "#4C0C0B", "#A0A0A0"))+
  labs(y = "Proportion of time") +
theme(axis.title.x = element_text(size=12))+
xlab("Impala type & location") +
  scale_x_discrete(limits= c( "female.wits.facility", "male.wits.facility", "juvenile.wits.facility", "female.kruger", "male.kruger"), labels=c("Female.WRF", "Male.WRF", "Juvenile.WRF", "Female.KNP", "Male.KNP"))
Figure.2


## Bachelor herds
# Need to convert everything to long format
imp.23.male.long <- imp.23.male.sum %>%
  pivot_longer(
    cols = c("foraging", "vigilant", "all.other"),
    names_to = "Behavior",
    values_to = "Count"
  )

# Need to get total observations for each group to convert counts to proportions
imp.23.male.long <- imp.23.male.long %>%
   group_by(location, herd.type) %>%
  mutate(sum = sum(Count))

# Making a proportion column
imp.23.male.long$prop <- imp.23.male.long$Count/imp.23.male.long$sum

#Reoder and relavle behavior levels
imp.23.male.long$Behavior<-factor(imp.23.male.long$Behavior, levels=c("foraging", "vigilant", "all.other"), labels= c("Foraging", "Vigilance", "Other"))

# Making figure for males in territorial and bachelor herds
Figure.3 <- ggplot(data = imp.23.male.long, aes(y = prop, x= interaction(herd.type, location), fill = Behavior)) +
  geom_bar(position = "dodge", stat = "identity", alpha = .85) + 
  theme +
    scale_fill_manual(values = c("#488650", "#4C0C0B", "#A0A0A0"))+
    #scale_fill_manual(values = c("#365977", "#C0772B", "#A0A0A0"))+
  #scale_fill_manual(values = c("#C0532B", "#D5AB85", "#8C86A0"))+
  labs(y = "Proportion of time") + 
  theme(axis.title.x = element_text(size=12))+
xlab("Herd type & location") +
  scale_x_discrete(limits= c("territorial.wits.facility",  "bachelor.wits.facility", "territorial.kruger", "bachelor.kruger"), labels = c(  "Territorial.WRF","Bachelor.WRF", "Territorial.KNP","Bachelor.KNP"))
Figure.3

#ggsave("C:/Users/mwuen//Documents/R/Misc/Figure.1.png", Figure.1, units = "in", dpi = 300, width = 6.5, height = 3.5)

#ggsave("C:/Users/mwuen//Documents/R/Misc/Figure.2.png", Figure.2, units = "in", dpi = 300, width = 6.5, height = 3.5)

#ggsave("C:/Users/mwuen//Documents/R/Misc/Figure.3.png", Figure.3, units = "in", dpi = 300, width = 6.5, height = 3.5)

library(patchwork)
patchworkImpala=Figure.1+Figure.2+Figure.3 + plot_layout(ncol=1, nrow=3)
patchworkImpala+ 
    plot_annotation(tag_levels = 'A') &
    theme(plot.tag = element_text(size = 12, face="bold"))
#ggsave("C:/Users/mwuen//Documents/R/Misc/CombinedFigure.png", units=c("in"), width=6.5, height=8)


```